# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34ef80db91f0b1e6707864bed81d2595f3c118b7eea6a35b55025e2248804d74f68dc37b17e14aa1d4f2e2164916312452f45fbed8f24ac909a84746ec0f280

test:
  secret_key_base: 06d58d68b45708bf8faf338a69108af497b71dc153e987ad38ee6f8227214a043b4517799ee4f821a173780cdd62e9b3113f9c12835efc91d6b65b9f916bd8e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
